---
title: "Curriculum Vitae"
---

[[Download as PDF](files/academic_cv.pdf)]

::: {.panel-tabset}
## Education

::: {.callout collapse="true"}
### PhD, Department of Statistics [07/2025 - now]{style="float:right"}
* LMU München (DE)
* Focus: Neurosymbolic Architectures for Trustworthy ML
* Social Data Science and AI Lab (SODA)
* Advisor: Prof. Dr. Christoph Kern

[[Website](https://www.stat.lmu.de/soda)]
:::

::: {.callout collapse="true"}
### M.Sc. Computing in the Humanities [10/2021 - 09/2024]{style="float:right"}
* University of Bamberg (DE)
* Focus: Cognitive Systems
* Thesis: *Tree-Vitality Classification from Image Data: A Comparison of Multispectral Index Scores and Deep Learning Approaches* (Grade: 1.0)
* Advisor: Prof. Dr. Ute Schmid
* Final grade: 1.3

[[Website](https://www.uni-bamberg.de/kogsys/)]
:::

::: {.callout collapse="true"}
### European Summer School on Artificial Intelligence [07/2023]{style="float:right"}
* University of Ljubljana (SI)
* Selected topics:
  * Neurosymbolic AI
  * Uncertainty in Sequential Decision Making*
  * Planning and RL
  * AI for Science

[[Website](https://www.essai.si)]
:::

::: {.callout collapse="true"}
### Erasmus Exchange [09/2022 - 02/2023]{style="float:right"}
* University of Dubrovnik (HR)

[[Website](https://www.unidu.hr/)]
:::

::: {.callout collapse="true"}
### B.Sc. Psychology [10/2018 - 09/2022]{style="float:right"}
* University of Bamberg (DE)
* Thesis: *Affecting Insight: The Influence of Negative Affect on Creative and Analytic Thought* (Grade: 1.3)
* Advisor: Prof. Dr. Jascha Rüsseler
* Final grade: 2.0
:::

## Professional

::: {.callout collapse="true"}
### ondatix Datenwerkstatt GmbH [04/2026 - now]{style="float:right"}
* *Co-founder*
* Data Science and AI Consulting and Software Development for the Public Sector
* Located in Munich (DE)

[[Website](https://www.ondatix.de)]
[[GitHub](https://github.com/ondatix)]
:::

::: {.callout collapse="true"}
### Social Data Science and AI Lab (SODA), LMU München [02/2025 - now]{style="float:right"}
* *Academic Employee*
* Member of the ADA initiative that organises data analysis workshops and support for public authorities
* Research on neurosymbolic architectures for trustworthy ML
* Co-organisation of the Datafest hackathon at LMU Münchend AI Consulting and Software Development for the Public Sector

[[Website](https://www.stat.lmu.de/soda)]
:::

::: {.callout collapse="true"}
### Social Data Science and AI Lab (SODA), LMU München [10/2024 - 02/2025]{style="float:right"}
* *Freelance Data Scientist*
* Assistance in the ADA workshop series on applied data analysis for public authorities in Bavaria
* Planning of an infrastructure solution for storage and processing of geo-spatial data in Bavarian public authorities
* Development of a Shiny application that aids archivists in the task of court record sampling

[[Website](https://www.stat.lmu.de/soda)]
:::

::: {.callout collapse="true"}
### Bytabo GmbH [02/2024 - 07/2024]{style="float:right"}
* *Data Scientist and AI Engineer (Trainee)*
* Engineering of Python-backends
* Training and deployment of Machine Learning models for price regression (CatBoost) and time series prediction (LSTM)
* Development of RAG interfaces
* LLM Finetuning
:::

::: {.callout collapse="true"}
### Chair of Cognitive Systems, University of Bamberg [06/2023 - 09/2023]{style="float:right"}
* *Teaching Assistant*
* Introduction to Artificial Intelligence (Bachelor level)
* Concipation and correction of assignments
* Tutorials for ∼40 students

[[Website](https://www.uni-bamberg.de/kogsys/)]
:::

::: {.callout collapse="true"}
### Chair of Privacy and Security in Information Systems, University of Bamberg [04/2023 - 09/2023]{style="float:right"}
* *Teaching Assistant*
* Introduction to Computer Architectures and Operating Systems (Bachelor level)
* Tutorials for ∼15 students

[[Website](https://www.uni-bamberg.de/psi/)]
:::

## Publications

::: {.panel-tabset}
### In Review

::: {.callout collapse="true"}
#### Neurosymbolic Architcetures for Algorithmic Fairness
*Kestel, L.*, & Kern, C. (2026). *Neurosymbolic Architectures for Algorithmic Fairness*.

[[Preprint](https://neurosymbolic-ai-journal.com/paper/neurosymbolic-architectures-algorithmic-fairness-0)][[Illustration](https://kestelnadomu.github.io/nesy_bimi_illustration/)]

<!-- Citation:
```{.bibtex}
@article{kestel_nesybimi2026,
  title={Neurosymbolic Architcetures for Algorithmic Fairness},
  author={Kestel, Leonhard and Kern, Christoph},
  year={2026}
}
``` -->
:::

### Accepted / Published

::: {.callout collapse="true"}
##### A Neurosymbolic Approach to Counterfactual Fairness
Heilmann, X., Manganini, C., Cerrato, M., *Kestel, L.*, & Belle, V. (2026). *A Neurosymbolic Approach to Counterfactual Fairness*.

[[Preprint](https://neurosymbolic-ai-journal.com/paper/neurosymbolic-approach-counterfactual-fairness-0)]

<!-- Citation:
```{.bibtex}
@article{heilmann_nesycf2026,
  title={A Neurosymbolic Approach to Counterfactual Fairness},
  author={Heilmann, Xenia and Manganini, Chiara and Cerrato, Mattia and Kestel, Leonhard and Belle, Vaishak},
  year={2026}
}
``` -->
:::
:::

## Teaching

::: {.callout collapse="true"}
### Statistical Software 2 for the Statistics Minor [Summer 2026]{style="float:right"}
* Lecturer,Instructor
* LMU München
* Bachelor level
:::

::: {.callout collapse="true"}
### Statistical Software 1 for the Statistics Minor [Winter 25/26]{style="float:right"}
* Lecturer, Instructor
* LMU München
* Bachelor level
:::

::: {.callout collapse="true"}
### Statistics 2 for the Statistics Minor [Summer 2025]{style="float:right"}
* Instructor
* LMU München
* Bachelor level
:::

::: {.callout collapse="true"}
### Introduction to Artificial Intelligence [Summer 2023]{style="float:right"}
* Teaching Assistant
* University of Bamberg
* Bachelor level
:::

::: {.callout collapse="true"}
### Computer Architectures and Operating Systems [Summer 2023]{style="float:right"}
* Teaching Assistant
* University of Bamberg
* Bachelor level
:::

## Other Activities

::: {.callout collapse="true"}
### Büro Grandezza e.V. [2025 - now]{style="float:right"}
* Role: Advisory board member
* Organisation: Non-profit organisation for the promotion of culture and arts

[[Website](https://www.buero-grandezza.de)]
:::

::: {.callout collapse="true"}
### make IT project [2023 - 2024]{style="float:right"}
* Role: Mentor to secondary school students on opportunities and fundamentals of a degree in computer science
* Organisation: Equal Opportunity Office (University of Bamberg)

[[Website](https://www.uni-bamberg.de/make-it/)]
:::

::: {.callout collapse="true"}
### Student Council [2023 - 2024]{style="float:right"}
* Role: Member, Treasurer
* Organisation: Faculty of Human Sciences and Education (University of Bamberg)

[[Website](https://www.uni-bamberg.de/huwi/personen-und-einrichtungen/fachschaft-huwi/)]
:::

::: {.callout collapse="true"}
### Family Support Service [2018 - 2022]{style="float:right"}
* Role: Carer for people with intellectual disabilities 
* Organisation: Lebenshilfe gGmbH (Munich and Bamberg)

[[Website](https://www.lebenshilfe.de/)]
:::

::: {.callout collapse="true"}
### Voluntary Gap Year [2017 - 2018]{style="float:right"}
* Role: Carer for people with intellectual disabilities 
* Organisation: OBA München

[[Website](https://www.oba-muenchen.de/)]
:::

::: {.callout collapse="true"}
### Lutheran Youth Organisation Munich (EJM) [2014 - now]{style="float:right"}
* Role: Organizing role in children’s and youth camps  
* Organisation: Lutheran Youth Organisation Munich (EJM)

[[Website](https://www.ej-muenchen.de/)]
:::

:::
